### PR TITLE
Avoid restricting the SCI by prescribing a specific metric.

### PR DESCRIPTION
**Pull request by ciril-emaps**
We are hereby submitting a formal proposal to amend the SCI standard.

From the evidence gathered, it seems like there is currently little consensus on which metric to use as a decision-making signal, as can be seen in these examples below (some of them are taken from [this discussion](https://github.com/Green-Software-Foundation/sci/discussions/351) in this forum):

- This paper by Hittinger recommends marginal ([link](https://pubs.acs.org/doi/abs/10.1021/acs.est.2c02344), [twitter thread](https://twitter.com/ElephantEating/status/1590741977880211458), [another twitter discussion thread](https://twitter.com/AukeHoekstra/status/1620525739803291648))
- This [letter](https://www.pnas.org/doi/10.1073/pnas.2211624119) and [paper](https://www.cell.com/iscience/fulltext/S2589-0042(22)00185-7?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2589004222001857%3Fshowall%3Dtrue) by Gagnon further highlights the shortcomings of marginal and compares it to other potential signals
- Upcoming EU regulation makes use of average emission factors [to document whether hydrogen has been electrolyzed using clean electricity](https://ec.europa.eu/commission/presscorner/detail/en/ip_23_594)

Even though more evidence could be collected, the examples above highlight that mandating the use of a specific metric in the SCI seems to be an unnecessary restriction that might hinder the adoption of the SCI:
- There is growing evidence of companies today wishing to use different decarbonisation signals within the Carbon Aware SDK of the GSF (e.g. marginal, average, carbon free electricity share) to decarbonise their software usage. A restrictive SCI would be a factor prohibiting certain companies from using the SDK. 
- The current restrictions of the SCI make it difficult for companies to adopt the SCI in order to reach their science-based targets (SBTi) and comply with the Greenhouse Gas Protocol.
- Finally, different signals are available in different regions and thus, restricting SCI to a specific signal unnecessarily confines the adoption of the SCI to regions where this specific signal is available.

In the interest of a credible, robust and globally applicable SCI, we suggest making the SCI less restrictive, by not mandating marginal as the only decision-making signal. Instead, we suggest allowing multiple, equally relevant metrics in the SCI. Such a change facilitates the adoption of the SCI globally and provides companies with a more broadly applicable tool to decarbonise software.

We recognize the motivation of having a single signal in the standard, and would therefore like to express our intention in helping the group follow and stay aligned with the upcoming scientific consensus, with the ultimate goal to make the SCI more impact-driven and globally applicable.

### CODE REVIEW

**Comment by Henry-WattTime** [comment]
Hello @ciril-emaps 
I have some serious reservations about this proposal. Fundamentally, we are trying to create a specification that encourages action to reduce global emissions (what might be considered 'consequential', but used to inform action). This proposed PR does not maintain that intent. 

I agree with Pieter Gagnon's letter that a short run marginal does not capture the full effect of load and renewable procurement activities. Pieter's letter calls for consideration of long run effects in decision making (a long run marginal signal), he does not advocate for any particular signal. We think that there could be many signals that might approximate that. I've tried to address this in PR #352 by making it clear that the marginal signal should include both short and long run effects. 

I think there is consensus that a marginal emissions signal is the correct signal for making decisions to reduce emissions (Olivier's blog post agrees with this and correctly identifies that long run marginal is hard to identify and that average emissions in this context is just a proxy for long run marginal). Am I misunderstanding your point here? If not, a discussion of good signals for long run marginal might make sense in the guidance document. 

Also, more granular data is not necessarily required for compliance with this standard. An organization can still make very informed siting decisions based on less granular data. For example, if an organization is making a decision on where to site computation load between Poland and France, annual data may be sufficient to make that decision, especially if load flexibility is not an option. Granular/hourly data alone should not be required if time-based load shifting decisions are being made. Global annual marginal emissions data (both operating and build margin) can be found from the [UNFCCC](https://unfccc.int/climate-action/sectoral-engagement/ifis-harmonization-of-standards-for-ghg-accounting/ifi-twg-list-of-methodologies), making this more accessible in a broader range of regions.

I don't particularly understand the bearing that other standards like the EU hydrogen standard has on this standard? I think this standard is attempting to measure something different and drive different action, especially because it includes market measures like renewable energy procurement, which the SCI explicitly excludes?

Does this make sense? Looking forward to discussing this in more depth.

**Comment by ciril-emaps** [comment]
Hi @Henry-WattTime 

Many thanks for your comments. From what you wrote, I actually do not think that we are in disagreement here. This PR was indeed prepared with the intent of encouraging action to reduce global emissions. This is why we'd like the standard to allow the use of multiple metrics such as marginal, average, renewable potential profiles, as long as they, as you mentioned, serve as a proxy to quantifying long-run impact.

To elaborate, given what you wrote, we seem to be in agreement that currently, several proxies exist for long-term impact, including, but not limited to:
- Short-run marginal (being a proxy as it does not capture the full long-term effects)
- Average (being a proxy for long-term impact)

To make it absolutely clear, this PR is to enable the use of other proxies, alongside the (short-run) marginal metric, as long as they are indeed leading to long-term impact.

Offering further clarification, we showcased the example of the EU regulation to highlight that other parts of the world are following other signals than currently allowed in the SCI. This specific regulation is creating a legal requirement about siting and load-shifting of electrolyzers, much in the same way that the SCI is incentivising going with software.

Regarding temporal granularity, we did not realise the SCI was not intending to mandate hourly emission factors - we were confused by the mention of “regional, granular marginal emissions rate” line 99. I believe it would be beneficial to provide more clarity around that, but happy to remove this from our pull request if controversial. 

Hope this clears up the misunderstanding and I am looking forward to our discussion in the WG.

**Review by SaraEmilyBergman — COMMENTED** [review]
I would suggest removing "hourly" as it is in direct conflict with the [Core characteristics
](https://github.com/Green-Software-Foundation/sci/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#core-characteristics)

**Comment by atg-abhishek** [comment]
Were there any actions to be taken on this PR @ciril-emaps based on the discussion in this week's SWG meeting? Thanks!

**Comment by atg-abhishek** [comment]
No worries, thanks for the update @ciril-emaps !

**Comment by navveenb** [comment]
One suggestion would be to list use cases where various signals apply. This would be helpful for partitioners to make decisions. In certain cases, this decision might even be abstracted through APIs-
For instance -
1.  An application would like to calculate SCI daily end of the day, which signal should be used.
2. An application would like to calculate SCI trends over the last 15 or 30 days. 
3. An application would like to schedule jobs in next 24-48 hrs and would like to run when carbon intensity is lowest.
4. An application would like to calculate SCI every X minutes (near real-time) and make certain decisions based on utilization and carbon intensity
5. The grid data is only available or reported every X intervals (i.e 6 months, yearly), which signal to use

**Comment by atg-abhishek** [comment]
Great suggestion @navveenb :)

**Comment by Henry-WattTime** [comment]
WG approved pull request #358 which addresses this.

**Pull request closed without merging**
