### PR TITLE
Updating Main from v1.0 to v1.1

### PR DESCRIPTION
**Pull request by seanmcilroy29**
WG has agreed to the changes in Dev and has approved to update of the SCI in Main from v1.0 to v1.1

**DO NOT MERGE UNTIL APPROVED AFTER REVIEW - 18 APR**

### CODE REVIEW

**Comment by akshitbatra** [comment]
**[Suggestion]**

Hey Team, 
As we are planning to move from v1.0 to v1.1, could we maintain a [Change Log](https://keepachangelog.com/en/1.1.0/) file in the repository so it's easily trackable on what all has been changed from one version to another.

**Comment by seanmcilroy29** [comment]
@akshitbatra - v1.1 and all future version updates will have their own feature release notes

**Comment by Henry-WattTime** [comment]
Also, Sean very generously made a direct comparison that resolved many of the file name changes so you can see just the text changes: https://github.com/Green-Software-Foundation/sci/compare/1.0-comparison...1.1-comparison

**Comment by seanmcilroy29** [comment]
No Comments have been submitted during the review period.
WG has now agreed to merge this PR if no submissions are added by 18 Apr

**Pull request merged**
